#ifndef __COMMON_H__
#define __COMMON_H__
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <stdint.h>
#include <limits.h>
#include <ctype.h>
#include <stdarg.h>
#include <stddef.h>
#include <assert.h>
#include <stdbool.h>
#include <windows.h>
#include <math.h>
//#include <cmath>
//#include <cstdio>
//#include <cstdlib>
//#include <cstring>
//#include <string>
//#include <ctime>
//#include <cstdint>
//#include <cstdarg>
//#include <cstdbool>
//#include <climits>
#include <vector>
#include <stack>
#include <queue>
//#include <list>
//#include <cctype>
//#include <cstddef>
//#include <algorithm>
//#include <cassert>
//#include <map>
//#include <bitset>
//#include <cerrno>
#include <iostream>
using namespace std;
#pragma warning(disable:6031)
#endif//!__COMMON_H__